### ISSUE TITLE
Check working with ruby 1.9.3.

### ISSUE THREAD

**Issue by kslazarev** [kslazarev/numbers_and_words#4]
ruby-1.9.3-p0-fast :001 > require 'numbers_and_words'
 => true 
ruby-1.9.3-p0-fast :002 > 177.to_words
NoMethodError: undefined method `capacity_count' for [7, 7, 1]:Array
